apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-post-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      podLabel: api-post-pod-label
  template:
    metadata:
      labels:
        podLabel: api-post-pod-label
    spec:
      containers:
        - name: api-post-pod-cont
          image: api-post-img:v1.0.0
          imagePullPolicy: Never
