# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage2-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  hostPath:
    path: "/mnt/storage2"
  capacity:
    storage: 1Gi
