apiVersion: v1
kind: Service
metadata:
  name: db-post-mongo-svc
spec:
  type: ClusterIP
  selector:
    podLabel: db-post-mongo-pod-label
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
