apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-photo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      podLabel: api-photo-pod-label
  template:
    metadata:
      labels:
        podLabel: api-photo-pod-label
    spec:
      containers:
        - name: api-photo-pod-cont
          image: api-photo-img:v1.0.0
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              value: "mongodb://db-photo-mongo-svc.app1-ns.svc.cluster.local:27017/photo-db"
